[dev]
    command = 'yarn dev'
    framework = '#custom'
    port = 8888
    targetPort = 3000
    autoLaunch = true

[build]
    command = 'astro build'
    functions = 'netlify/functions'
    publish = 'dist'

[functions]
    node_bundler = 'esbuild'
    included_files = ['data/**']
    external_node_modules = ["astro"]

[[ redirects ]]
    from = '/api/*'
    to = '/.netlify/functions/:splat'
    status = 200
    force = true
