[dev]
    command = 'yarn dev'
    framework = '#custom'
    port = 8888
    targetPort = 3000
    autoLaunch = true

[build]
    command = 'yarn build'
    functions = 'functions/'
    publish = 'dist'

[functions]
    node_bundler = 'esbuild'
    included_files = ['data/**']

[[ redirects ]]
    from = '/api/*'
    to = '/.netlify/functions/:splat'
    status = 200
    force = true
